### ISSUE TITLE
ts declaration

### ISSUE THREAD

**Issue by diadal** [Seokky/vue-pincode-input#13]
Try `npm install @types/vue-pincode-input` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-pincode-input';`

**Comment by Seokky** [comment]
If be honest, i don't know which is the right way to make this plugin typescript-friendly. It is used only in markup, does it really needs to declare some types? Let me know.

**Comment by jameshhood** [comment]
I use typescript and unless you're trying to wrap a component into your own component library, this is unneeded. I was able to just add the library to my project, and import it directly into my component using it. @diadal Can you elaborate what you're trying to do? I guess by now you've already figured it out or moved on

**Comment by andercard** [comment]
You can try the following if typescript generates an error when importing the module

``` js
// Route
// root/shims-vue.d.ts

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}


// add line
declare module 'vue-pincode-input';
```
