### ISSUE TITLE
Fields not cleanning when I set v-model as null or ''

### ISSUE THREAD

**Issue by JonataCSantos** [Seokky/vue-pincode-input#15]
I'm trying to clean the fields by setting v-model as null or '', but the field keeps with the value even though the v-model now has its value cleaned.

**Comment by Seokky** [comment]
@JonataCSantos Hi, thank you for the issue. I have published version 0.3.0 for this problem, so you need to update package.

**Comment by JonataCSantos** [comment]
Worked pretty fine after correction! Thank you, @Seokky !
