### ISSUE TITLE
type 

### ISSUE THREAD

**Issue by slickben** [Seokky/vue-pincode-input#18]
not working with nuxt 

getting Cannot use import statement outside a module

**Comment by jameshhood** [comment]
I have it working with nuxt just fine. How are you trying to use it?

**Comment by eLoyyyyy** [comment]
I can't get it to work with `nuxt.js@2.15.6` either.

```
// plugins/pincode-input.js
import Vue from 'vue';
import PincodeInput from 'vue-pincode-input';

Vue.component(PincodeInput);
```

```
// nuxt.config.js
export default {
   ...
   plugins: [
      ...
      '~/plugins/pincode-input.js'
   ]
   ...
}
```

same error message, `SyntaxError: Cannot use import statement outside a module`

**Comment by alekseyburn** [comment]
> I can't get it to work with `nuxt.js@2.15.6` either.
> 
> ```
> // plugins/pincode-input.js
> import Vue from 'vue';
> import PincodeInput from 'vue-pincode-input';
> 
> Vue.component(PincodeInput);
> ```
> 
> ```
> // nuxt.config.js
> export default {
>    ...
>    plugins: [
>       ...
>       '~/plugins/pincode-input.js'
>    ]
>    ...
> }
> ```
> 
> same error message, `SyntaxError: Cannot use import statement outside a module`

try to use this:

```
import Vue from 'vue'
import PincodeInput from 'vue-pincode-input'

Vue.component('PincodeInput', PincodeInput)
```


```
plugins: [
    ...
    {
      src: '@/plugins/vue-pincode-input',
      mode: 'client'
    }
  ]
```
  
  for me work's fine
