### ISSUE TITLE
cuztomization of regex

### ISSUE THREAD

**Issue by stephsalou** [Seokky/vue-pincode-input#6]
difficult to customize if you can give the option to add new regex rules
because your regex rules only let some charchere pass if like me you want to use lodash debounce to display

the user's password a few seconds before replacing it with special chars it is complex

**Comment by Seokky** [comment]
@stephsalou Hi, man. Thank you for the suggestion. It is really good idea. I'll add some property for this purpose soon.

**Comment by Seokky** [comment]
@stephsalou now you can use new properties - **characterPreview** and **previewDuration**. Learn more in readme. 

P.S.: don't forget to update package to 0.2.0.
