### ISSUE TITLE
Browser CDN and Global example

### ISSUE THREAD

**Issue by amchconsult** [Seokky/vue-pincode-input#8]
can you give an example of use on CDN as global component.

thank you

**Comment by Seokky** [comment]
@amchconsult Hi, this plugin isn't available on cdn. You can register this component globally in your main.js same way like any other component. Do you want to use it in Vue app, right?

**Comment by amchconsult** [comment]
Well, I am using direct html, it is not a vue-cli.

**Comment by Seokky** [comment]
@amchconsult Ohh, sorry. Right now vue-pincode-input available only within vue-cli applications.

**Comment by amchconsult** [comment]
Thank you.
