### ISSUE TITLE
When setting the length of the pin code input, it errors out

### ISSUE THREAD

**Issue by BenHall-1** [Seokky/vue-pincode-input#9]
Hey,

I've set the `PincodeInput` to 6 via `<PincodeInput v-model="code" length='6' />` and it creates the boxes fine, however in the console I get the following error:
```
[Vue warn]: Invalid prop: type check failed for prop "length". Expected Number with value 6, got String with value "6".

found in

---> <PincodeInput>
       <VStepperContent>
         <VStepper>
           <OnboardingStepper> at resources/js/components/onboarding/OnboardingStepper.vue
             <VContent>
               <VApp>
                 <Root>
```

Any idea?

Thanks :D

**Comment by Seokky** [comment]
>  Expected Number with value 6, got String with value "6"

Hi, you need to pass number instead of string.
`:length="6"` instead of `length="6"`
